### ISSUE TITLE
Escenarios de pruebas

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#583]
- [x] Si no se ha subido ningún Inventario debo ver un mensaje diciendo que me hacen falta completar los pasos 1 y 2 ( ver #584 )
- [x] Si no se ha Generado el Plan de Apertura debo ver un mensaje diciendo que me hacen falta completar el paso 2 ( ver #585 )
- [x] Como funcionario debo ver un conjunto para el Inventario de Datos ( ver #586 )
- [x] Como funcionario debo ver un conjunto para el Plan de Apertura ( ver #587 )
- [x] Como funcionario debo ver la lista de conjuntos marcados como `Público` en el Inventario ( ver #588 )
- [x] Como funcionario debo ver la lista de conjuntos ordenados ascendentemente por la columna de `Fecha compromiso` ( ver #590 )
- [x] Como sistema se debe prellenar la información de los conjuntos de datos. ( ver #592 )
- [x] Como funcionario puedo actualizar los datos del conjunto ( ver #593 )
- [x] Como funcionario puedo documentar los datos de un recurso( ver #594 )
- [ ] Como sistema se debe validar que se hayan documentado todos los datos del recurso al `Guardar Avance`
- [x] Previo a publicar los recursos debo visualizar los conjuntos y recursos que se van a publicar ( ver #624 )
- [x] Como funcionario puedo publicar recursos ( ver #625 ) 
- [ ] Como funcionario debo poder ver el último comprobante de publicación de datos
- [ ] Como funcionario puedo actualizar el Inventario y se deberá reflejar en el catálogo ( ver #609 )
- [ ] Como funcionario puedo actualizar el Plan de Apertura y se deberá reflejar en el catálogo ( ver #610 )

**Comment by abisosa** [comment]
@camara podrías ser más específico en cada escenario porfa? Por ejemplo en:  "Si no se ha subido ningún Inventario debo ver un mensaje diciendo que me hacen falta completar los pasos 1 y 2", dónde se verìa ese mensaje?

**Comment by carlosmaya** [comment]
@abisosa si .. si, aqui solo ando poniendo la lista, ya estoy creando un issue por cada caso con pantallas para este más claro =)

**Comment by abisosa** [comment]
@camara sorry, no sabía. Muchas gracias :)

**Comment by rodowi** [comment]
¿qué pasa cuando el funcionario decide actualizar su inventario?
¿qué pasa cuando no le asigno sector a un dataset y quiero publicar?

**Comment by carlosmaya** [comment]
¿qué pasa cuando un Admin actualiza los datos de la Organización? ¿cómo debería impactar en el catálogo?
